 ### Name - Rathang Rajpal
 ### NET ID - RXR210009
 ### Course - CS 6364
 ### Course Name - Artificial Intelligence
 ### Section number - 002
 ### Assignment 4 - Cliff Walking Problem using DFS

### Importing the required libraries

In [1]:
import numpy as np
import math

### Defining a play area of size 6,10

In [2]:
Play_area = np.zeros((6,10))
Play_area

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### initializing the play area with the values given in the question

In [3]:
def initialize():
    Play_area = np.zeros((6,10))
    for i in range(Play_area.shape[0]):
        for j in range(Play_area.shape[1]):
            if(i==5 and j>0 and j<9):
                Play_area[i][j] = math.inf
            elif((i>=2 and i<=4) and ((j<=3 and j>=1) or (j<=7 and j>=5))):
                Play_area[i][j] = 5
            elif(i==5 and j==0):
                Play_area[i][j] = 0
            else:
                Play_area[i][j] = 1
    return Play_area


In [4]:
x = initialize()

### This is the initial state of the world given to us in the question

In [5]:
x

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  5.,  5.,  5.,  1.,  5.,  5.,  5.,  1.,  1.],
       [ 1.,  5.,  5.,  5.,  1.,  5.,  5.,  5.,  1.,  1.],
       [ 1.,  5.,  5.,  5.,  1.,  5.,  5.,  5.,  1.,  1.],
       [ 0., inf, inf, inf, inf, inf, inf, inf, inf,  1.]])

### initializing a disctionary to store information about every node that our agent might go on
### * It has values like parent to check the previous node/ parent node for every node
### * It stores if a node has been visited yet or not
### * It even stores the cost to reach to that particular node

In [6]:
data_dict = {}
for i in range(Play_area.shape[0]):
        for j in range(Play_area.shape[1]):
            data_dict[(i,j)] = {'parent': None, 'cost_to_reach': 0, 'visited':False}

In [7]:
data_dict[(0,0)]

{'parent': None, 'cost_to_reach': 0, 'visited': False}

### Initializing the agent to the start point which is (5,0) or (6,1) as we have 0 based indexing

In [8]:
start = (5,0)
data_dict[start]['visited'] = True
nodes = [start]

### Creating a function that returns all the possible neigbors for a given position

In [9]:
def valid_neighbors_dfs(curr):
  neighbors = [(curr[0]-1,curr[1]), (curr[0],curr[1]+1), (curr[0]+1,curr[1]), (curr[0],curr[1]-1)]
  res = []
  for i in neighbors:
    if i[0]==5 and (i[1]<=8 and i[1]>=1):
      continue
    if(i[0]<6 and i[0]>=0) and (i[1]>=0 and i[1]<10):
      res.append(i)
  return res

### Run the algorithm untill GOAL state is reached which in our case is (5,9)

In [10]:
while(True):
    current = nodes.pop()
    if(current == (5,9)):
        break
    # print(current)
    neighbors = valid_neighbors_dfs(current)
    # print(neighbors)
    for i in neighbors:
        if(data_dict[i]['visited'] == False):
            nodes.append(i)
            data_dict[i]['visited'] = True
            data_dict[i]['parent'] = current
            data_dict[i]['cost_to_reach'] = x[i[0]][i[1]] + data_dict[current]['cost_to_reach']
            break

In [11]:
Play_area = initialize()

In [12]:
for i in range(Play_area.shape[0]):
        for j in range(Play_area.shape[1]):
            Play_area[i][j] = data_dict[(i,j)]['cost_to_reach']

### Area explored by DFS

In [13]:
Play_area

array([[ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 16.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 17.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 18.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 19.]])

In [18]:
DFS_Path = [(5,9)]
while True:
    curr = DFS_Path[-1]
    if(data_dict[curr]['parent']==None):
        break
    DFS_Path.append(data_dict[curr]['parent'])
DFS_Path.reverse()

### Path returned after DFS traversal

In [19]:
print(*DFS_Path)

(5, 0) (4, 0) (3, 0) (2, 0) (1, 0) (0, 0) (0, 1) (0, 2) (0, 3) (0, 4) (0, 5) (0, 6) (0, 7) (0, 8) (0, 9) (1, 9) (2, 9) (3, 9) (4, 9) (5, 9)


### Depicting the Path traversed by our agent

In [16]:
Path_traversed = np.zeros((6,10))
for i in DFS_Path:
    Path_traversed[i] = data_dict[(i[0],i[1])]['cost_to_reach']
Path_traversed

array([[ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 16.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 17.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 18.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 19.]])

## Cost to reach the GOAL

In [17]:
print(data_dict[(5,9)]['cost_to_reach'])

19.0
